version: '3'

services:
    api:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        container_name: api
        # depends_on:
            # - postgres
        networks:
            php-network:
                ipv4_address: 12.0.0.8

    # postgres:
    #     image: postgres
    #     restart: always
    #     container_name: postgres
    #     ports:
    #         - 5432:5432
    #     environment:
    #         - POSTGRES_DB=postgres
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=postgres
    #     volumes:
    #         - ./data/db:/var/lib/postgresql/data
    #     networks:
    #         php-network:
    #             ipv4_address: 12.0.0.9
    
    # mailhog:
    #     image: mailhog/mailhog
    #     container_name: mailhog
    #     ports:
    #         - 1025:1025
    #         - 8025:8025
    #     networks:
    #          php-network:
    #             ipv4_address: 12.0.0.10
    
    # redis:
    #     image: redis
    #     container_name: redis
    #     ports:
    #         - 6379:6379
    #     networks:
    #         php-network:
    #             ipv4_address: 12.0.0.9

networks:
    php-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "12.0.0.0/16"