version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        container_name: pkg_nginx
        depends_on:
            - php
            - mysql
        networks:
            - pgk-network

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./:/var/www/html
        container_name: pkg_php
        networks:
            - pgk-network

    mysql:
        image: mysql:5.7
        restart: always
        container_name: pkg_mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
            - ./dockerDBData:/var/lib/mysql
        networks:
            pgk-network:
                ipv4_address: 15.0.0.8
    
    # redis:
    #     image: redis
    #     container_name: pkg_redis
    #     ports:
    #         - 6379:6379
    #     networks:
    #         pgk-network:
    #             ipv4_address: 15.0.0.9

networks:
    pgk-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "15.0.0.0/16"